blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/aaione/omnipowers/discussions
    about: For usage questions, troubleshooting help, and general discussion, please visit our Discussions instead of opening an issue.
